{% set version = "2.0.0" %}
{% set sha256 = "d44aef9f698f98c2b1ba5c29ee0ba967aaefb1a141a4c3244de4dabfc7ad9fd9" %}

package:
  name: flask-bower
  version: '{{ version }}'

source:
  url: https://pypi.python.org/packages/source/F/Flask-Bower/Flask-Bower-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - flask >=0.9

test:
  imports:
    - flask_bower

about:
  home: https://github.com/lobeck/flask-bower
  license: GPL-2.0
  license_file: LICENSE.md
  license_family: GPL
  summary: An extension to manage and serve your javascript assets with bower

extra:
  recipe-maintainers:
    - corburn
