travis:
  secure:
    BINSTAR_TOKEN: DBCJbRAl2nwxkF1JoVvndO+jA+IVTbRHmIQDozU45qHcA1wNsqXW4mKAAvHwSaGr/+IwIrQYSijNK6eq5O0ixTBTFyI5yqWKcYZP79BNbCoXa/bC2JBC8lw3t/tIueq6KbUvb+iJpY/SBeHWfFiKeVv607R6dhsUBnGaVjU6acDPYfIQBfjS6AmSrANBWtImfn7hWdcEv3Y06UhhLm21nQr2jGhdUBTMJatA7QED5XItnZFgngTpzEdcUM5DiY4LldkQP5RpeipQCaud67b0jI0vEtH7lpoPJOLB/bNkQ7g6GC48GrMDpzdGLvIckvosrwn+CiKFQ1dWBtacZLqVi0W8vWEwNse6YMl/QOF0DkG60wlFH1WcwevXGsTb3TQXgt/eS8bLtW2CAd0/iNj3zrLQxFJnrL9vqRzIXnxw7xnEhSylmXmVGp1NGRXD2wqcNL8mQ9mTwUZ3eToqSPdTSWQHTk7K744kUfqSJy9RkCc7v94hoSanyqGFbeYQ4VVRpZkFSdwEc41IiDwmQ+86wUXA4R+iAH7ijw+4BTTPfhVAbkK6QHSPNoniZXI7NyJyqpHkrKlLvVsW5f4SsOaE98p/L67h9V7LL0TKAlanQtc+RSB8qEyNJUx6LBccz3Gx6FE0g2LApS8r08sETQCFKklspAQFiZs3tffU1GRC4xc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
