travis:
  secure:
    BINSTAR_TOKEN: aPgGYpBADjX7XIg0qjvxTB+CKH38rfoqq4+jTqLA3/Qk9YqyRf37600U4ulKxW3bsEwkUNQumM7+dRUjZ+MCov/ZPxGYxDdCQ/EoI8YhdafOHf8WD98/c7EFtBGWm7XPgSQZprtYidcvqKDAd+t6HRO26TApd8SXjrhi9/YyLCsP01j2Es3bQjAWrhei9xVv+2fIV+yXKrvUfZtmIVNa/9ZJ4vu/7GKyi3xesmrWwoZNOJS9QDVJUVRjjj3NwPQLK/DcOoF/Y/xOfHDXPpOelw86lIHwcZQIOIJKUEjItJwuIoF/tm65jYShMmYECbK2woBp3HTgrBYSVgrW3mHQ0trppu1SlDmvkuR5k7YqOpODwIF0zACZ1qJcwdWABiboUxCSwdgg77CzGrBVQmEBFK9XSNcp+nKFQEr6GqsyPLS2+OxhGrcebyTTFw4P50dwAPG7JSXLTNub3ViWSj7QqJwOVs1/DFNmqH6t8rnj4UjVbpN1Bctp1V5TyH1Nn65r/l1/6BZrujFsSVAQnjxZwssdMFtM7+8S5D4Mt8oO05RenX4ilNNXm7Py+8R50r+Y2B+IxQVYOblSGVr9Y2E5TSC5vQY8tUq7lFoAR3D+piI4VhtNI0aLgC+pi4I4GR3QdupZZFZdnseSfRBl8skNezod9af07Vdk0GWZaBIVCbQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
